"""
DO NOT MODIFY THIS FILE MANUALLY
This file was generated by reflectapi-cli

Schema name: Demo application
This is a demo application
"""

from __future__ import annotations


# Standard library imports
import warnings
from collections.abc import AsyncIterator, Iterator
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Generic, Literal, Optional, TypeVar, Union

# Third-party imports
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    model_serializer,
    model_validator,
)

# Runtime imports
from reflectapi_runtime import AsyncClientBase, ClientBase, ApiResponse
from reflectapi_runtime import ReflectapiEmpty
from reflectapi_runtime import ReflectapiPartialModel
from reflectapi_runtime import (
    parse_externally_tagged as _parse_externally_tagged,
    serialize_externally_tagged as _serialize_externally_tagged,
)


# Type variables for generic types


T = TypeVar("T")


# External type definitions
StdNumNonZeroU32 = Annotated[int, "Rust NonZero u32 type"]
StdNumNonZeroU64 = Annotated[int, "Rust NonZero u64 type"]
StdNumNonZeroI32 = Annotated[int, "Rust NonZero i32 type"]
StdNumNonZeroI64 = Annotated[int, "Rust NonZero i64 type"]


class MyapiModelInputPet(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=(), defer_build=True
    )

    name: str = Field(description="identity")
    kind: myapi.model.Kind = Field(description="kind of pet")
    age: int | None = Field(default=None, description="age of the pet")
    updated_at: datetime | None = None
    behaviors: list[myapi.model.Behavior] | None = Field(
        default=None, description="behaviors of the pet"
    )


# Public aliases for this module
Pet = MyapiModelInputPet

__all__ = ["MyapiModelInputPet", "Pet"]
