"""
DO NOT MODIFY THIS FILE MANUALLY
This file was generated by reflectapi-cli

Schema name: Demo application
This is a demo application
"""

from __future__ import annotations


from . import myapi

from .myapi import (
    MyapiHealthCheckFail,
    MyapiOrderCoverageRequest,
    MyapiOrderCoverageResponse,
)

from . import myapi

from .myapi.coverage import (
    MyapiCoverageBaseModel,
    MyapiCoverageDeepOption,
    MyapiCoverageDefaultedField,
    MyapiCoverageEmptyStruct,
    MyapiCoverageGenericTree,
    MyapiCoverageIntKeyedMap,
    MyapiCoverageKeywordVariants,
    MyapiCoverageKeywordVariantsClass,
    MyapiCoverageKeywordVariantsLambda,
    MyapiCoverageKeywordVariantsReturn,
    MyapiCoverageMutualA,
    MyapiCoverageMutualB,
    MyapiCoveragePyKeywordFields,
    MyapiCoveragePydanticReservedFields,
    MyapiCoverageRequest,
    MyapiCoverageResponse,
    MyapiCoverageShadowingFields,
    MyapiCoverageTreeNode,
    MyapiCoverageWeirdDocstring,
    MyapiCoverageWrapper,
)

from . import myapi

from .myapi.model import (
    MyapiModelBehavior,
    MyapiModelBehaviorAggressiveVariant,
    MyapiModelBehaviorOtherVariant,
    MyapiModelKind,
    MyapiModelKindBird,
    MyapiModelKindCat,
    MyapiModelKindDog,
)

from . import myapi

from .myapi.model.input import MyapiModelInputPet

from . import myapi

from .myapi.model.output import MyapiModelOutputPet

from . import myapi

from .myapi.order import MyapiOrderInsertData, MyapiOrderPolicy, MyapiOrderRateLimit

from . import myapi

from .myapi.proto import (
    MyapiProtoHeaders,
    MyapiProtoInternalError,
    MyapiProtoPaginated,
    MyapiProtoPetsCreateError,
    MyapiProtoPetsCreateErrorInvalidIdentityVariant,
    MyapiProtoPetsListError,
    MyapiProtoPetsListErrorInternal,
    MyapiProtoPetsListErrorInvalidCursor,
    MyapiProtoPetsListErrorUnauthorized,
    MyapiProtoPetsListRequest,
    MyapiProtoPetsRemoveError,
    MyapiProtoPetsRemoveRequest,
    MyapiProtoPetsUpdateError,
    MyapiProtoPetsUpdateErrorValidationVariant,
    MyapiProtoPetsUpdateRequest,
    MyapiProtoValidationA,
    MyapiProtoValidationError,
    MyapiProtoValidationErrorValidationAVariant,
)

from . import reflectapi

from .reflectapi import (
    ReflectapiOption,
    ReflectapiOptionNone,
    ReflectapiOptionSome,
    ReflectapiOptionUndefined,
)


def rebuild_models() -> None:
    myapi.myapi = myapi
    myapi.coverage.myapi = myapi
    myapi.model.myapi = myapi
    myapi.model.input.myapi = myapi
    myapi.model.output.myapi = myapi
    myapi.order.myapi = myapi
    myapi.proto.myapi = myapi
    reflectapi.reflectapi = reflectapi
    errors: list[str] = []
    for _model in [
        MyapiHealthCheckFail,
        MyapiOrderCoverageRequest,
        MyapiOrderCoverageResponse,
        MyapiCoverageBaseModel,
        MyapiCoverageRequest,
        MyapiCoverageResponse,
        MyapiCoverageDeepOption,
        MyapiCoverageDefaultedField,
        MyapiCoverageEmptyStruct,
        MyapiCoverageGenericTree,
        MyapiCoverageIntKeyedMap,
        MyapiCoverageKeywordVariants,
        MyapiCoverageMutualA,
        MyapiCoverageMutualB,
        MyapiCoveragePyKeywordFields,
        MyapiCoveragePydanticReservedFields,
        MyapiCoverageShadowingFields,
        MyapiCoverageTreeNode,
        MyapiCoverageWeirdDocstring,
        MyapiCoverageWrapper,
        MyapiModelBehavior,
        MyapiModelKind,
        MyapiModelInputPet,
        MyapiModelOutputPet,
        MyapiOrderInsertData,
        MyapiOrderPolicy,
        MyapiOrderRateLimit,
        MyapiProtoHeaders,
        MyapiProtoInternalError,
        MyapiProtoPaginated,
        MyapiProtoPetsCreateError,
        MyapiProtoPetsListError,
        MyapiProtoPetsListRequest,
        MyapiProtoPetsRemoveError,
        MyapiProtoPetsRemoveRequest,
        MyapiProtoPetsUpdateError,
        MyapiProtoPetsUpdateRequest,
        MyapiProtoValidationA,
        MyapiProtoValidationError,
    ]:
        if not hasattr(_model, "model_rebuild"):
            continue
        try:
            _model.model_rebuild()
        except Exception as exc:
            errors.append(f"  - {_model.__name__}: {type(exc).__name__}: {exc}")
    if errors:
        raise RuntimeError(
            "reflectapi: failed to rebuild "
            + str(len(errors))
            + " generated model(s). This usually means the codegen emitted an annotation pointing at a symbol that was never defined (a dangling type reference). Fix the codegen rather than catching this error.\n"
            + "\n".join(errors)
        )
