"""
DO NOT MODIFY THIS FILE MANUALLY
This file was generated by reflectapi-cli

Schema name: Demo application
This is a demo application
"""

from __future__ import annotations


from ._client import AsyncClient

from ._client import Client

from . import myapi

from .myapi import MyapiHealthCheckFail

from . import myapi

from .myapi.model import (
    MyapiModelBehavior,
    MyapiModelBehaviorAggressiveVariant,
    MyapiModelBehaviorOtherVariant,
    MyapiModelKind,
    MyapiModelKindBird,
    MyapiModelKindCat,
    MyapiModelKindDog,
)

from . import myapi

from .myapi.model.input import MyapiModelInputPet

from . import myapi

from .myapi.model.output import MyapiModelOutputPet

from . import myapi

from .myapi.proto import (
    MyapiProtoHeaders,
    MyapiProtoInternalError,
    MyapiProtoPaginated,
    MyapiProtoPetsCreateError,
    MyapiProtoPetsCreateErrorInvalidIdentityVariant,
    MyapiProtoPetsListError,
    MyapiProtoPetsListErrorInternal,
    MyapiProtoPetsListErrorInvalidCursor,
    MyapiProtoPetsListErrorUnauthorized,
    MyapiProtoPetsListRequest,
    MyapiProtoPetsRemoveError,
    MyapiProtoPetsRemoveRequest,
    MyapiProtoPetsUpdateError,
    MyapiProtoPetsUpdateErrorValidationVariant,
    MyapiProtoPetsUpdateRequest,
    MyapiProtoValidationA,
    MyapiProtoValidationError,
    MyapiProtoValidationErrorValidationAVariant,
)

from . import reflectapi

from .reflectapi import (
    ReflectapiOption,
    ReflectapiOptionNone,
    ReflectapiOptionSome,
    ReflectapiOptionUndefined,
)

from ._rebuild import rebuild_models as _rebuild_models

_rebuild_models()

__all__ = [
    "AsyncClient",
    "Client",
    "MyapiHealthCheckFail",
    "MyapiModelBehavior",
    "MyapiModelBehaviorAggressiveVariant",
    "MyapiModelBehaviorOtherVariant",
    "MyapiModelInputPet",
    "MyapiModelKind",
    "MyapiModelKindBird",
    "MyapiModelKindCat",
    "MyapiModelKindDog",
    "MyapiModelOutputPet",
    "MyapiProtoHeaders",
    "MyapiProtoInternalError",
    "MyapiProtoPaginated",
    "MyapiProtoPetsCreateError",
    "MyapiProtoPetsCreateErrorInvalidIdentityVariant",
    "MyapiProtoPetsListError",
    "MyapiProtoPetsListErrorInternal",
    "MyapiProtoPetsListErrorInvalidCursor",
    "MyapiProtoPetsListErrorUnauthorized",
    "MyapiProtoPetsListRequest",
    "MyapiProtoPetsRemoveError",
    "MyapiProtoPetsRemoveRequest",
    "MyapiProtoPetsUpdateError",
    "MyapiProtoPetsUpdateErrorValidationVariant",
    "MyapiProtoPetsUpdateRequest",
    "MyapiProtoValidationA",
    "MyapiProtoValidationError",
    "MyapiProtoValidationErrorValidationAVariant",
    "ReflectapiOption",
    "ReflectapiOptionNone",
    "ReflectapiOptionSome",
    "ReflectapiOptionUndefined",
]
