[workspace]
members = [
    "reflect",
    "reflect-cli",
    "reflect-demo",
    "reflect-demo/clients/rust",
    "reflect-derive",
    "reflect-schema",
]
resolver = "2"

[workspace.dependencies]
reflect = { path = "reflect" }
reflect-derive = { path = "reflect-derive" }
reflect-schema = { path = "reflect-schema" }
