[package]
name = "reflect-axum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflect = { workspace = true, features = ["uuid"] }
reflect-endpoint = { workspace = true }

axum = "0.7.4"
