"""
DO NOT MODIFY THIS FILE MANUALLY
This file was generated by reflectapi-cli

Schema name: Demo application
This is a demo application
"""

from __future__ import annotations


# Standard library imports
import warnings
from collections.abc import AsyncIterator, Iterator
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Generic, Literal, Optional, TypeVar, Union

# Third-party imports
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    model_serializer,
    model_validator,
)

# Runtime imports
from reflectapi_runtime import AsyncClientBase, ClientBase, ApiResponse
from reflectapi_runtime import ReflectapiDuration
from reflectapi_runtime import ReflectapiEmpty
from reflectapi_runtime import ReflectapiInfallible
from reflectapi_runtime import ReflectapiPartialModel
from reflectapi_runtime import (
    parse_externally_tagged as _parse_externally_tagged,
    serialize_externally_tagged as _serialize_externally_tagged,
)


# Type variables for generic types


C = TypeVar("C")

T = TypeVar("T")


# External type definitions
StdNumNonZeroU32 = Annotated[int, "Rust NonZero u32 type"]
StdNumNonZeroU64 = Annotated[int, "Rust NonZero u64 type"]
StdNumNonZeroI32 = Annotated[int, "Rust NonZero i32 type"]
StdNumNonZeroI64 = Annotated[int, "Rust NonZero i64 type"]


class MyapiOrderInsertData(BaseModel):
    """Bug 1 (namespace alias mismatch). The struct name starts with
    the parent namespace\\'s cap (`Order…`) — the alias-stripping
    pass used to strip the leading cap from the namespace alias
    (`order.InsertData = OrderInsertData`) while field annotations
    kept the un-stripped form, producing `order.OrderInsertData`
    which doesn\\'t resolve at `model_rebuild()` time."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    identity: str
    alternative_part_number: tuple[str, str] | None = Field(
        default=None,
        description="Bug 2 (tuple types). serde emits Rust tuples as JSON arrays;\nthe Python codegen used to emit `std.tuple.Tuple2[...]`\nwith no matching class, so any reference broke at rebuild.",
    )


class MyapiOrderPolicy(BaseModel, Generic[C, T]):
    """Bug 4 (PhantomData). PhantomData has no wire data — serde
    skips it. The codegen used to emit `std.marker.PhantomData[T]`
    as a field annotation, leaving a dangling reference."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str


class MyapiOrderRateLimit(BaseModel):
    """Bug 3 (Duration shape). serde emits `Duration` as
    `{\\"secs\\": <u64>, \\"nanos\\": <u32>}`. Pydantic\\'s `timedelta`
    validator rejects that shape, so any response with a Duration
    failed validation."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    retry_after: ReflectapiDuration
    max_wait: ReflectapiDuration | None = None


# Public aliases for this module
InsertData = MyapiOrderInsertData
OrderInsertData = MyapiOrderInsertData
Policy = MyapiOrderPolicy
RateLimit = MyapiOrderRateLimit

__all__ = [
    "InsertData",
    "MyapiOrderInsertData",
    "MyapiOrderPolicy",
    "MyapiOrderRateLimit",
    "OrderInsertData",
    "Policy",
    "RateLimit",
]
