'''
Generated Python client for api_client.

DO NOT MODIFY THIS FILE MANUALLY.
This file is automatically generated by ReflectAPI.
'''

from __future__ import annotations


# Standard library imports
import warnings
from collections.abc import AsyncIterator, Iterator
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Generic, Literal, Optional, TypeVar, Union

# Third-party imports
from pydantic import BaseModel, ConfigDict, Field, RootModel, model_serializer, model_validator

# Runtime imports
from reflectapi_runtime import AsyncClientBase, ClientBase, ApiResponse
from reflectapi_runtime import ReflectapiEmpty
from reflectapi_runtime import ReflectapiOption


# Helper functions for externally tagged enum serialization/deserialization
def _parse_externally_tagged(data, variants: dict, types: tuple, enum_name: str):
    """Parse an externally tagged enum from {key: value} format."""
    if types and isinstance(data, types):
        return data
    if isinstance(data, str) and data in variants:
        handler = variants[data]
        if handler == "_unit":
            return data
    if isinstance(data, dict):
        if len(data) != 1:
            raise ValueError("Externally tagged enum must have exactly one key")
        key, value = next(iter(data.items()))
        if key in variants:
            handler = variants[key]
            if handler == "_unit":
                return key
            return handler(value)
    raise ValueError(f"Unknown variant for {enum_name}: {data}")


def _serialize_externally_tagged(root, serializers: dict, enum_name: str):
    """Serialize an externally tagged enum to {key: value} format."""
    for variant_name, (check, serialize) in serializers.items():
        if check(root):
            return serialize(root)
    raise ValueError(f"Cannot serialize {enum_name} variant: {type(root)}")


# Type variables for generic types


T = TypeVar("T")


# External type definitions
StdNumNonZeroU32 = Annotated[int, "Rust NonZero u32 type"]
StdNumNonZeroU64 = Annotated[int, "Rust NonZero u64 type"]
StdNumNonZeroI32 = Annotated[int, "Rust NonZero i32 type"]
StdNumNonZeroI64 = Annotated[int, "Rust NonZero i64 type"]


class MyapiModelBehaviorAggressiveVariant(BaseModel):
    """Aggressive variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    field_0: float = Field(description="aggressiveness level")
    field_1: str = Field(description="some notes")


class MyapiModelBehaviorOtherVariant(BaseModel):
    """Other variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    description: str = Field(description="Custom provided description of a behavior")
    notes: str | None = Field(default=None, description="Additional notes\nUp to a user to put free text here")


# Externally tagged enum using RootModel
MyapiModelBehaviorVariants = Union[Literal["Calm"], MyapiModelBehaviorAggressiveVariant, MyapiModelBehaviorOtherVariant]

class MyapiModelBehavior(RootModel[MyapiModelBehaviorVariants]):
    """Externally tagged enum"""

    @model_validator(mode='before')
    @classmethod
    def _validate(cls, data):
        return _parse_externally_tagged(data, {"Calm": "_unit", "Aggressive": lambda v: MyapiModelBehaviorAggressiveVariant(field_0=v[0], field_1=v[1]) if isinstance(v, list) else (_ for _ in ()).throw(ValueError("Expected list for tuple variant Aggressive")), "Other": lambda v: MyapiModelBehaviorOtherVariant(**v)}, (MyapiModelBehaviorAggressiveVariant, MyapiModelBehaviorOtherVariant), "MyapiModelBehavior")

    @model_serializer
    def _serialize(self):
        return _serialize_externally_tagged(self.root, {"Calm": (lambda r: r == "Calm", lambda r: "Calm"), "Aggressive": (lambda r: isinstance(r, MyapiModelBehaviorAggressiveVariant), lambda r: {"Aggressive": [r.field_0, r.field_1]}), "Other": (lambda r: isinstance(r, MyapiModelBehaviorOtherVariant), lambda r: {"Other": r.model_dump(by_alias=True)})}, "MyapiModelBehavior")

class MyapiModelKindDog(BaseModel):
    """A dog"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal['dog'] = Field(default="dog", description="Discriminator field")
    breed: str = Field(description="breed of the dog")


class MyapiModelKindCat(BaseModel):
    """A cat"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal['cat'] = Field(default="cat", description="Discriminator field")
    lives: int = Field(description="lives left")


class MyapiModelKindBird(BaseModel):
    """Test for unit variants in internally tagged enums"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal['bird'] = Field(default="bird", description="Discriminator field")


class MyapiModelKind(RootModel):
    root: Annotated[Union[MyapiModelKindDog, MyapiModelKindCat, MyapiModelKindBird], Field(discriminator='type')]


# Public aliases for this module
Behavior = MyapiModelBehavior
BehaviorAggressiveVariant = MyapiModelBehaviorAggressiveVariant
BehaviorOtherVariant = MyapiModelBehaviorOtherVariant
Kind = MyapiModelKind
KindBird = MyapiModelKindBird
KindCat = MyapiModelKindCat
KindDog = MyapiModelKindDog

from . import input
from . import output

__all__ = ["Behavior", "BehaviorAggressiveVariant", "BehaviorOtherVariant", "Kind", "KindBird", "KindCat", "KindDog", "MyapiModelBehavior", "MyapiModelBehaviorAggressiveVariant", "MyapiModelBehaviorOtherVariant", "MyapiModelKind", "MyapiModelKindBird", "MyapiModelKindCat", "MyapiModelKindDog", "input", "output"]
