"""
Generated Python client for api_client.

DO NOT MODIFY THIS FILE MANUALLY.
This file is automatically generated by ReflectAPI.
"""

from __future__ import annotations


# Standard library imports
from datetime import datetime
from enum import Enum
import warnings
from typing import Annotated, Any, Generic, Literal, Optional, TypeVar, Union

# Third-party imports
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PrivateAttr,
    RootModel,
    model_serializer,
    model_validator,
)

# Runtime imports
from reflectapi_runtime import AsyncClientBase, ClientBase, ApiResponse
from reflectapi_runtime import ReflectapiOption
from reflectapi_runtime import ReflectapiEmpty
from reflectapi_runtime.testing import MockClient, create_api_response


# Type variables for generic types


T = TypeVar("T")


class MyapiHealthCheckFail(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)


class MyapiProtoPetsRemoveError(str, Enum):
    """Generated enum."""

    NOT_FOUND = "NotFound"
    NOT_AUTHORIZED = "NotAuthorized"


class MyapiProtoHeaders(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    authorization: str


class MyapiProtoInternalError(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    message: str


class MyapiProtoPetsCreateErrorInvalidIdentityVariant(BaseModel):
    """InvalidIdentity variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    message: str


# Externally tagged enum using RootModel
MyapiProtoPetsCreateErrorVariants = Union[
    Literal["Conflict"],
    Literal["NotAuthorized"],
    MyapiProtoPetsCreateErrorInvalidIdentityVariant,
]


class MyapiProtoPetsCreateError(RootModel[MyapiProtoPetsCreateErrorVariants]):
    """Externally tagged enum"""

    @model_validator(mode="before")
    @classmethod
    def _validate_externally_tagged(cls, data):
        # Handle direct variant instances (for programmatic creation)
        if isinstance(data, MyapiProtoPetsCreateErrorInvalidIdentityVariant):
            return data

        # Handle JSON data (for deserialization)
        if isinstance(data, str) and data == "Conflict":
            return data
        if isinstance(data, str) and data == "NotAuthorized":
            return data

        if isinstance(data, dict):
            if len(data) != 1:
                raise ValueError("Externally tagged enum must have exactly one key")

            key, value = next(iter(data.items()))
            if key == "InvalidIdentity":
                return MyapiProtoPetsCreateErrorInvalidIdentityVariant(**value)

        raise ValueError(f"Unknown variant for MyapiProtoPetsCreateError: {data}")

    @model_serializer
    def _serialize_externally_tagged(self):
        if self.root == "Conflict":
            return "Conflict"
        if self.root == "NotAuthorized":
            return "NotAuthorized"
        if isinstance(self.root, MyapiProtoPetsCreateErrorInvalidIdentityVariant):
            return {"InvalidIdentity": self.root.model_dump()}

        raise ValueError(
            f"Cannot serialize MyapiProtoPetsCreateError variant: {type(self.root)}"
        )


class MyapiProtoPetsRemoveRequest(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str


class MyapiProtoValidationA(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    message: str


class MyapiProtoPaginated(BaseModel, Generic[T]):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    items: list[T]
    cursor: str | None = None


class MyapiProtoPetsListRequest(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    limit: int | None = None
    cursor: str | None = None


class MyapiProtoPetsListErrorInvalidCursor(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    kind: Literal["InvalidCursor"] = "InvalidCursor"


class MyapiProtoPetsListErrorUnauthorized(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    kind: Literal["Unauthorized"] = "Unauthorized"


class MyapiProtoPetsListErrorInternal(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    kind: Literal["Internal"] = "Internal"
    message: str


class MyapiProtoPetsListError(RootModel):
    root: Annotated[
        Union[
            MyapiProtoPetsListErrorInvalidCursor,
            MyapiProtoPetsListErrorUnauthorized,
            MyapiProtoPetsListErrorInternal,
        ],
        Field(discriminator="kind"),
    ]


class MyapiProtoValidationErrorValidationAVariant(BaseModel):
    """ValidationA variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    field_0: myapi.proto.ValidationA


# Externally tagged enum using RootModel
MyapiProtoValidationErrorVariants = MyapiProtoValidationErrorValidationAVariant


class MyapiProtoValidationError(RootModel[MyapiProtoValidationErrorVariants]):
    """Externally tagged enum"""

    @model_validator(mode="before")
    @classmethod
    def _validate_externally_tagged(cls, data):
        # Handle direct variant instances (for programmatic creation)
        if isinstance(data, MyapiProtoValidationErrorValidationAVariant):
            return data

        # Handle JSON data (for deserialization)

        if isinstance(data, dict):
            if len(data) != 1:
                raise ValueError("Externally tagged enum must have exactly one key")

            key, value = next(iter(data.items()))
            if key == "ValidationA":
                return MyapiProtoValidationErrorValidationAVariant(field_0=value)

        raise ValueError(f"Unknown variant for MyapiProtoValidationError: {data}")

    @model_serializer
    def _serialize_externally_tagged(self):
        if isinstance(self.root, MyapiProtoValidationErrorValidationAVariant):
            return {"ValidationA": self.root.field_0}

        raise ValueError(
            f"Cannot serialize MyapiProtoValidationError variant: {type(self.root)}"
        )


class MyapiProtoPetsUpdateRequest(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str
    kind: myapi.model.Kind | None = None
    age: ReflectapiOption[int] = None
    behaviors: ReflectapiOption[list[myapi.model.Behavior]] = None


class MyapiProtoPetsUpdateErrorValidationVariant(BaseModel):
    """Validation variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    field_0: list[myapi.proto.ValidationError]


# Externally tagged enum using RootModel
MyapiProtoPetsUpdateErrorVariants = Union[
    Literal["NotFound"],
    Literal["NotAuthorized"],
    MyapiProtoPetsUpdateErrorValidationVariant,
]


class MyapiProtoPetsUpdateError(RootModel[MyapiProtoPetsUpdateErrorVariants]):
    """Externally tagged enum"""

    @model_validator(mode="before")
    @classmethod
    def _validate_externally_tagged(cls, data):
        # Handle direct variant instances (for programmatic creation)
        if isinstance(data, MyapiProtoPetsUpdateErrorValidationVariant):
            return data

        # Handle JSON data (for deserialization)
        if isinstance(data, str) and data == "NotFound":
            return data
        if isinstance(data, str) and data == "NotAuthorized":
            return data

        if isinstance(data, dict):
            if len(data) != 1:
                raise ValueError("Externally tagged enum must have exactly one key")

            key, value = next(iter(data.items()))
            if key == "Validation":
                return MyapiProtoPetsUpdateErrorValidationVariant(field_0=value)

        raise ValueError(f"Unknown variant for MyapiProtoPetsUpdateError: {data}")

    @model_serializer
    def _serialize_externally_tagged(self):
        if self.root == "NotFound":
            return "NotFound"
        if self.root == "NotAuthorized":
            return "NotAuthorized"
        if isinstance(self.root, MyapiProtoPetsUpdateErrorValidationVariant):
            return {"Validation": self.root.field_0}

        raise ValueError(
            f"Cannot serialize MyapiProtoPetsUpdateError variant: {type(self.root)}"
        )


class MyapiModelBehaviorAggressiveVariant(BaseModel):
    """Aggressive variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    field_0: float
    field_1: str


class MyapiModelBehaviorOtherVariant(BaseModel):
    """Other variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    description: str
    notes: str | None = None


# Externally tagged enum using RootModel
MyapiModelBehaviorVariants = Union[
    Literal["Calm"], MyapiModelBehaviorAggressiveVariant, MyapiModelBehaviorOtherVariant
]


class MyapiModelBehavior(RootModel[MyapiModelBehaviorVariants]):
    """Externally tagged enum"""

    @model_validator(mode="before")
    @classmethod
    def _validate_externally_tagged(cls, data):
        # Handle direct variant instances (for programmatic creation)
        if isinstance(data, MyapiModelBehaviorAggressiveVariant):
            return data
        if isinstance(data, MyapiModelBehaviorOtherVariant):
            return data

        # Handle JSON data (for deserialization)
        if isinstance(data, str) and data == "Calm":
            return data

        if isinstance(data, dict):
            if len(data) != 1:
                raise ValueError("Externally tagged enum must have exactly one key")

            key, value = next(iter(data.items()))
            if key == "Aggressive":
                if isinstance(value, list):
                    return MyapiModelBehaviorAggressiveVariant(
                        field_0=value[0], field_1=value[1]
                    )
                else:
                    raise ValueError("Expected list for tuple variant Aggressive")
            if key == "Other":
                return MyapiModelBehaviorOtherVariant(**value)

        raise ValueError(f"Unknown variant for MyapiModelBehavior: {data}")

    @model_serializer
    def _serialize_externally_tagged(self):
        if self.root == "Calm":
            return "Calm"
        if isinstance(self.root, MyapiModelBehaviorAggressiveVariant):
            return {"Aggressive": [self.root.field_0, self.root.field_1]}
        if isinstance(self.root, MyapiModelBehaviorOtherVariant):
            return {"Other": self.root.model_dump()}

        raise ValueError(
            f"Cannot serialize MyapiModelBehavior variant: {type(self.root)}"
        )


class MyapiModelKindDog(BaseModel):
    """A dog"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal["dog"] = "dog"
    breed: str


class MyapiModelKindCat(BaseModel):
    """A cat"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal["cat"] = "cat"
    lives: int


class MyapiModelKindBird(BaseModel):
    """Test for unit variants in internally tagged enums"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal["bird"] = "bird"


class MyapiModelKind(RootModel):
    root: Annotated[
        Union[MyapiModelKindDog, MyapiModelKindCat, MyapiModelKindBird],
        Field(discriminator="type"),
    ]


class MyapiModelInputPet(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str
    kind: myapi.model.Kind
    age: int | None = None
    updated_at: datetime | None = None
    behaviors: list[myapi.model.Behavior] | None = None


class MyapiModelOutputPet(BaseModel):
    """Generated data model."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str
    kind: myapi.model.Kind
    age: int | None = None
    updated_at: datetime
    behaviors: list[myapi.model.Behavior] | None = None


# Namespace classes for dotted access to types
class myapi:
    """Namespace for myapi types."""

    HealthCheckFail = MyapiHealthCheckFail

    class proto:
        """Namespace for proto types."""

        PetsRemoveError = MyapiProtoPetsRemoveError
        Headers = MyapiProtoHeaders
        InternalError = MyapiProtoInternalError
        PetsCreateErrorInvalidIdentityVariant = (
            MyapiProtoPetsCreateErrorInvalidIdentityVariant
        )
        PetsCreateError = MyapiProtoPetsCreateError
        PetsRemoveRequest = MyapiProtoPetsRemoveRequest
        ValidationA = MyapiProtoValidationA
        Paginated = MyapiProtoPaginated
        PetsListRequest = MyapiProtoPetsListRequest
        PetsListErrorInvalidCursor = MyapiProtoPetsListErrorInvalidCursor
        PetsListErrorUnauthorized = MyapiProtoPetsListErrorUnauthorized
        PetsListErrorInternal = MyapiProtoPetsListErrorInternal
        PetsListError = MyapiProtoPetsListError
        ValidationErrorValidationAVariant = MyapiProtoValidationErrorValidationAVariant
        ValidationError = MyapiProtoValidationError
        PetsUpdateRequest = MyapiProtoPetsUpdateRequest
        PetsUpdateErrorValidationVariant = MyapiProtoPetsUpdateErrorValidationVariant
        PetsUpdateError = MyapiProtoPetsUpdateError

    class model:
        """Namespace for model types."""

        BehaviorAggressiveVariant = MyapiModelBehaviorAggressiveVariant
        BehaviorOtherVariant = MyapiModelBehaviorOtherVariant
        Behavior = MyapiModelBehavior
        KindDog = MyapiModelKindDog
        KindCat = MyapiModelKindCat
        KindBird = MyapiModelKindBird
        Kind = MyapiModelKind

        class input:
            """Namespace for input types."""

            Pet = MyapiModelInputPet

        class output:
            """Namespace for output types."""

            Pet = MyapiModelOutputPet


class AsyncHealthClient:
    """Async client for health operations."""

    def __init__(self, client: AsyncClientBase) -> None:
        self._client = client

    async def check(
        self,
    ) -> ApiResponse[Any]:
        """Check the health of the service

        Returns:
            ApiResponse[Any]: Response containing Any data
        """
        path = "/health.check"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            response_model=None,
        )


class AsyncPetsClient:
    """Async client for pets operations."""

    def __init__(self, client: AsyncClientBase) -> None:
        self._client = client

    async def create(
        self,
        data: Optional[myapi.model.input.Pet] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any]:
        """Create a new pet

        Args:
            data: Request data for the create operation.

        Returns:
            ApiResponse[Any]: Response containing Any data
        """
        path = "/pets.create"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
        )

    async def delete(
        self,
        data: Optional[myapi.proto.PetsRemoveRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any]:
        """Remove an existing pet

        Args:
            data: Request data for the delete operation.

        Returns:
            ApiResponse[Any]: Response containing Any data

        .. deprecated::
           Use pets.remove instead
        """

        warnings.warn(
            "pets_delete is deprecated: Use pets.remove instead",
            DeprecationWarning,
            stacklevel=2,
        )

        path = "/pets.delete"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
        )

    async def get_first(
        self,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[myapi.model.output.Pet | None]:
        """Fetch first pet, if any exists

        Returns:
            ApiResponse[myapi.model.output.Pet | None]: Response containing myapi.model.output.Pet | None data
        """
        path = "/pets.get-first"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            headers_model=headers,
            response_model=myapi.model.output.Pet | None,
        )

    async def list(
        self,
        data: Optional[myapi.proto.PetsListRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[myapi.proto.Paginated[myapi.model.output.Pet]]:
        """List available pets

        Args:
            data: Request data for the list operation.

        Returns:
            ApiResponse[myapi.proto.Paginated[myapi.model.output.Pet]]: Response containing myapi.proto.Paginated[myapi.model.output.Pet] data
        """
        path = "/pets.list"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=myapi.proto.Paginated[myapi.model.output.Pet],
        )

    async def remove(
        self,
        data: Optional[myapi.proto.PetsRemoveRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any]:
        """Remove an existing pet

        Args:
            data: Request data for the remove operation.

        Returns:
            ApiResponse[Any]: Response containing Any data
        """
        path = "/pets.remove"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
        )

    async def update(
        self,
        data: Optional[myapi.proto.PetsUpdateRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any]:
        """Update an existing pet

        Args:
            data: Request data for the update operation.

        Returns:
            ApiResponse[Any]: Response containing Any data
        """
        path = "/pets.update"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
        )


class AsyncClient(AsyncClientBase):
    """Async client for the API."""

    def __init__(
        self,
        base_url: str,
        **kwargs: Any,
    ) -> None:
        super().__init__(base_url, **kwargs)

        self.health = AsyncHealthClient(self)

        self.pets = AsyncPetsClient(self)


class HealthClient:
    """Synchronous client for health operations."""

    def __init__(self, client: ClientBase) -> None:
        self._client = client

    def check(
        self,
    ) -> ApiResponse[Any]:
        """Check the health of the service

        Returns:
            ApiResponse[Any]: Response containing Any data
        """
        path = "/health.check"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            response_model=None,
        )


class PetsClient:
    """Synchronous client for pets operations."""

    def __init__(self, client: ClientBase) -> None:
        self._client = client

    def create(
        self,
        data: Optional[myapi.model.input.Pet] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any]:
        """Create a new pet

        Args:
            data: Request data for the create operation.

        Returns:
            ApiResponse[Any]: Response containing Any data
        """
        path = "/pets.create"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
        )

    def delete(
        self,
        data: Optional[myapi.proto.PetsRemoveRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any]:
        """Remove an existing pet

        Args:
            data: Request data for the delete operation.

        Returns:
            ApiResponse[Any]: Response containing Any data

        .. deprecated::
           Use pets.remove instead
        """

        warnings.warn(
            "pets_delete is deprecated: Use pets.remove instead",
            DeprecationWarning,
            stacklevel=2,
        )

        path = "/pets.delete"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
        )

    def get_first(
        self,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[myapi.model.output.Pet | None]:
        """Fetch first pet, if any exists

        Returns:
            ApiResponse[myapi.model.output.Pet | None]: Response containing myapi.model.output.Pet | None data
        """
        path = "/pets.get-first"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            headers_model=headers,
            response_model=myapi.model.output.Pet | None,
        )

    def list(
        self,
        data: Optional[myapi.proto.PetsListRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[myapi.proto.Paginated[myapi.model.output.Pet]]:
        """List available pets

        Args:
            data: Request data for the list operation.

        Returns:
            ApiResponse[myapi.proto.Paginated[myapi.model.output.Pet]]: Response containing myapi.proto.Paginated[myapi.model.output.Pet] data
        """
        path = "/pets.list"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=myapi.proto.Paginated[myapi.model.output.Pet],
        )

    def remove(
        self,
        data: Optional[myapi.proto.PetsRemoveRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any]:
        """Remove an existing pet

        Args:
            data: Request data for the remove operation.

        Returns:
            ApiResponse[Any]: Response containing Any data
        """
        path = "/pets.remove"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
        )

    def update(
        self,
        data: Optional[myapi.proto.PetsUpdateRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any]:
        """Update an existing pet

        Args:
            data: Request data for the update operation.

        Returns:
            ApiResponse[Any]: Response containing Any data
        """
        path = "/pets.update"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
        )


class Client(ClientBase):
    """Synchronous client for the API."""

    def __init__(
        self,
        base_url: str,
        **kwargs: Any,
    ) -> None:
        super().__init__(base_url, **kwargs)

        self.health = HealthClient(self)

        self.pets = PetsClient(self)


# External type definitions
StdNumNonZeroU32 = Annotated[int, "Rust NonZero u32 type"]
StdNumNonZeroU64 = Annotated[int, "Rust NonZero u64 type"]
StdNumNonZeroI32 = Annotated[int, "Rust NonZero i32 type"]
StdNumNonZeroI64 = Annotated[int, "Rust NonZero i64 type"]

# Rebuild models to resolve forward references
try:
    myapi.HealthCheckFail.model_rebuild()
    myapi.model.Behavior.model_rebuild()
    myapi.model.Kind.model_rebuild()
    myapi.model.input.Pet.model_rebuild()
    myapi.model.output.Pet.model_rebuild()
    myapi.proto.Headers.model_rebuild()
    myapi.proto.InternalError.model_rebuild()
    myapi.proto.Paginated.model_rebuild()
    myapi.proto.PetsCreateError.model_rebuild()
    myapi.proto.PetsListError.model_rebuild()
    myapi.proto.PetsListRequest.model_rebuild()
    myapi.proto.PetsRemoveError.model_rebuild()
    myapi.proto.PetsRemoveRequest.model_rebuild()
    myapi.proto.PetsUpdateError.model_rebuild()
    myapi.proto.PetsUpdateRequest.model_rebuild()
    myapi.proto.ValidationA.model_rebuild()
    myapi.proto.ValidationError.model_rebuild()
except AttributeError:
    # Some types may not have model_rebuild method
    pass


# Factory classes (generated after model rebuild to avoid forward references)
class myapi_model_BehaviorFactory:
    """Factory class for creating myapi.model.Behavior variants with ergonomic syntax.

    myapi.model.Behavior variants
    """

    @staticmethod
    def calm() -> myapi.model.Behavior:
        """Creates the 'Calm' variant of the myapi.model.Behavior enum."""
        return myapi.model.Behavior("Calm")

    @staticmethod
    def aggressive(field_0: float, field_1: str) -> myapi.model.Behavior:
        """Creates the 'Aggressive' variant of the myapi.model.Behavior enum."""
        return myapi.model.Behavior(
            myapi.model.BehaviorAggressiveVariant(field_0=field_0, field_1=field_1)
        )

    @staticmethod
    def other(description: str, notes: str | None = None) -> myapi.model.Behavior:
        """Creates the 'Other' variant of the myapi.model.Behavior enum."""
        return myapi.model.Behavior(
            myapi.model.BehaviorOtherVariant(description=description, notes=notes)
        )


class myapi_proto_PetsCreateErrorFactory:
    """Factory class for creating myapi.proto.PetsCreateError variants with ergonomic syntax.

    myapi.proto.PetsCreateError variants
    """

    @staticmethod
    def conflict() -> myapi.proto.PetsCreateError:
        """Creates the 'Conflict' variant of the myapi.proto.PetsCreateError enum."""
        return myapi.proto.PetsCreateError("Conflict")

    @staticmethod
    def not_authorized() -> myapi.proto.PetsCreateError:
        """Creates the 'NotAuthorized' variant of the myapi.proto.PetsCreateError enum."""
        return myapi.proto.PetsCreateError("NotAuthorized")

    @staticmethod
    def invalid_identity(message: str) -> myapi.proto.PetsCreateError:
        """Creates the 'InvalidIdentity' variant of the myapi.proto.PetsCreateError enum."""
        return myapi.proto.PetsCreateError(
            myapi.proto.PetsCreateErrorInvalidIdentityVariant(message=message)
        )


class myapi_model_KindFactory:
    """Factory class for creating myapi.model.Kind variants with ergonomic syntax.

    myapi.model.Kind variants
    """

    BIRD = myapi.model.KindBird()

    @staticmethod
    def dog(breed: str) -> myapi.model.KindDog:
        """Creates the 'dog' variant of the myapi.model.Kind enum."""
        return myapi.model.KindDog(breed=breed)

    @staticmethod
    def cat(lives: int) -> myapi.model.KindCat:
        """Creates the 'cat' variant of the myapi.model.Kind enum."""
        return myapi.model.KindCat(lives=lives)


class myapi_proto_PetsListErrorFactory:
    """Factory class for creating myapi.proto.PetsListError variants with ergonomic syntax.

    myapi.proto.PetsListError variants
    """

    INVALIDCURSOR = myapi.proto.PetsListErrorInvalidCursor()
    UNAUTHORIZED = myapi.proto.PetsListErrorUnauthorized()

    @staticmethod
    def internal(
        field_0: myapi.proto.InternalError,
    ) -> myapi.proto.PetsListErrorInternal:
        """Creates the 'Internal' variant of the myapi.proto.PetsListError enum."""
        return myapi.proto.PetsListErrorInternal(field_0=field_0)


class myapi_proto_ValidationErrorFactory:
    """Factory class for creating myapi.proto.ValidationError variants with ergonomic syntax.

    myapi.proto.ValidationError variants
    """

    @staticmethod
    def validation_a(field_0: myapi.proto.ValidationA) -> myapi.proto.ValidationError:
        """Creates the 'ValidationA' variant of the myapi.proto.ValidationError enum."""
        return myapi.proto.ValidationError(
            myapi.proto.ValidationErrorValidationAVariant(field_0=field_0)
        )


class myapi_proto_PetsUpdateErrorFactory:
    """Factory class for creating myapi.proto.PetsUpdateError variants with ergonomic syntax.

    myapi.proto.PetsUpdateError variants
    """

    @staticmethod
    def not_found() -> myapi.proto.PetsUpdateError:
        """Creates the 'NotFound' variant of the myapi.proto.PetsUpdateError enum."""
        return myapi.proto.PetsUpdateError("NotFound")

    @staticmethod
    def not_authorized() -> myapi.proto.PetsUpdateError:
        """Creates the 'NotAuthorized' variant of the myapi.proto.PetsUpdateError enum."""
        return myapi.proto.PetsUpdateError("NotAuthorized")

    @staticmethod
    def validation(
        field_0: list[myapi.proto.ValidationError],
    ) -> myapi.proto.PetsUpdateError:
        """Creates the 'Validation' variant of the myapi.proto.PetsUpdateError enum."""
        return myapi.proto.PetsUpdateError(
            myapi.proto.PetsUpdateErrorValidationVariant(field_0=field_0)
        )


# Testing utilities


def create_myapi_healthcheckfail_response(
    value: myapi.HealthCheckFail,
) -> ApiResponse[myapi.HealthCheckFail]:
    """Create a mock ApiResponse for myapi.HealthCheckFail."""
    return create_api_response(value)


def create_myapi_model_behavior_response(
    value: myapi.model.Behavior,
) -> ApiResponse[myapi.model.Behavior]:
    """Create a mock ApiResponse for myapi.model.Behavior."""
    return create_api_response(value)


def create_myapi_model_kind_response(
    value: myapi.model.Kind,
) -> ApiResponse[myapi.model.Kind]:
    """Create a mock ApiResponse for myapi.model.Kind."""
    return create_api_response(value)


def create_myapi_model_input_pet_response(
    value: myapi.model.input.Pet,
) -> ApiResponse[myapi.model.input.Pet]:
    """Create a mock ApiResponse for myapi.model.input.Pet."""
    return create_api_response(value)


def create_myapi_model_output_pet_response(
    value: myapi.model.output.Pet,
) -> ApiResponse[myapi.model.output.Pet]:
    """Create a mock ApiResponse for myapi.model.output.Pet."""
    return create_api_response(value)


def create_myapi_proto_headers_response(
    value: myapi.proto.Headers,
) -> ApiResponse[myapi.proto.Headers]:
    """Create a mock ApiResponse for myapi.proto.Headers."""
    return create_api_response(value)


def create_myapi_proto_internalerror_response(
    value: myapi.proto.InternalError,
) -> ApiResponse[myapi.proto.InternalError]:
    """Create a mock ApiResponse for myapi.proto.InternalError."""
    return create_api_response(value)


def create_myapi_proto_paginated_response(
    value: myapi.proto.Paginated,
) -> ApiResponse[myapi.proto.Paginated]:
    """Create a mock ApiResponse for myapi.proto.Paginated."""
    return create_api_response(value)


def create_myapi_proto_petscreateerror_response(
    value: myapi.proto.PetsCreateError,
) -> ApiResponse[myapi.proto.PetsCreateError]:
    """Create a mock ApiResponse for myapi.proto.PetsCreateError."""
    return create_api_response(value)


def create_myapi_proto_petslisterror_response(
    value: myapi.proto.PetsListError,
) -> ApiResponse[myapi.proto.PetsListError]:
    """Create a mock ApiResponse for myapi.proto.PetsListError."""
    return create_api_response(value)


def create_myapi_proto_petslistrequest_response(
    value: myapi.proto.PetsListRequest,
) -> ApiResponse[myapi.proto.PetsListRequest]:
    """Create a mock ApiResponse for myapi.proto.PetsListRequest."""
    return create_api_response(value)


def create_myapi_proto_petsremoveerror_response(
    value: myapi.proto.PetsRemoveError,
) -> ApiResponse[myapi.proto.PetsRemoveError]:
    """Create a mock ApiResponse for myapi.proto.PetsRemoveError."""
    return create_api_response(value)


def create_myapi_proto_petsremoverequest_response(
    value: myapi.proto.PetsRemoveRequest,
) -> ApiResponse[myapi.proto.PetsRemoveRequest]:
    """Create a mock ApiResponse for myapi.proto.PetsRemoveRequest."""
    return create_api_response(value)


def create_myapi_proto_petsupdateerror_response(
    value: myapi.proto.PetsUpdateError,
) -> ApiResponse[myapi.proto.PetsUpdateError]:
    """Create a mock ApiResponse for myapi.proto.PetsUpdateError."""
    return create_api_response(value)


def create_myapi_proto_petsupdaterequest_response(
    value: myapi.proto.PetsUpdateRequest,
) -> ApiResponse[myapi.proto.PetsUpdateRequest]:
    """Create a mock ApiResponse for myapi.proto.PetsUpdateRequest."""
    return create_api_response(value)


def create_myapi_proto_validationa_response(
    value: myapi.proto.ValidationA,
) -> ApiResponse[myapi.proto.ValidationA]:
    """Create a mock ApiResponse for myapi.proto.ValidationA."""
    return create_api_response(value)


def create_myapi_proto_validationerror_response(
    value: myapi.proto.ValidationError,
) -> ApiResponse[myapi.proto.ValidationError]:
    """Create a mock ApiResponse for myapi.proto.ValidationError."""
    return create_api_response(value)


def create_mock_client() -> MockClient:
    """Create a mock client for testing."""
    return MockClient()
