"""
Generated Python client for api_client.

DO NOT MODIFY THIS FILE MANUALLY.
This file is automatically generated by ReflectAPI.
"""

from __future__ import annotations


# Standard library imports
import warnings
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Generic, Literal, Optional, TypeVar, Union

# Third-party imports
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    model_serializer,
    model_validator,
)

# Runtime imports
from reflectapi_runtime import AsyncClientBase, ClientBase, ApiResponse
from reflectapi_runtime import ReflectapiEmpty
from reflectapi_runtime import ReflectapiOption


# Helper functions for externally tagged enum serialization/deserialization
def _parse_externally_tagged(data, variants: dict, types: tuple, enum_name: str):
    """Parse an externally tagged enum from {key: value} format."""
    if types and isinstance(data, types):
        return data
    if isinstance(data, str) and data in variants:
        handler = variants[data]
        if handler == "_unit":
            return data
    if isinstance(data, dict):
        if len(data) != 1:
            raise ValueError("Externally tagged enum must have exactly one key")
        key, value = next(iter(data.items()))
        if key in variants:
            handler = variants[key]
            if handler == "_unit":
                return key
            return handler(value)
    raise ValueError(f"Unknown variant for {enum_name}: {data}")


def _serialize_externally_tagged(root, serializers: dict, enum_name: str):
    """Serialize an externally tagged enum to {key: value} format."""
    for variant_name, (check, serialize) in serializers.items():
        if check(root):
            return serialize(root)
    raise ValueError(f"Cannot serialize {enum_name} variant: {type(root)}")


# Type variables for generic types


T = TypeVar("T")


class MyapiHealthCheckFail(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)


class MyapiModelBehaviorAggressiveVariant(BaseModel):
    """Aggressive variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    field_0: float = Field(description="aggressiveness level")
    field_1: str = Field(description="some notes")


class MyapiModelBehaviorOtherVariant(BaseModel):
    """Other variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    description: str = Field(description="Custom provided description of a behavior")
    notes: str | None = Field(
        default=None, description="Additional notes\nUp to a user to put free text here"
    )


# Externally tagged enum using RootModel
MyapiModelBehaviorVariants = Union[
    Literal["Calm"], MyapiModelBehaviorAggressiveVariant, MyapiModelBehaviorOtherVariant
]


class MyapiModelBehavior(RootModel[MyapiModelBehaviorVariants]):
    """Externally tagged enum"""

    @model_validator(mode="before")
    @classmethod
    def _validate(cls, data):
        return _parse_externally_tagged(
            data,
            {
                "Calm": "_unit",
                "Aggressive": lambda v: (
                    MyapiModelBehaviorAggressiveVariant(field_0=v[0], field_1=v[1])
                    if isinstance(v, list)
                    else (_ for _ in ()).throw(
                        ValueError("Expected list for tuple variant Aggressive")
                    )
                ),
                "Other": lambda v: MyapiModelBehaviorOtherVariant(**v),
            },
            (MyapiModelBehaviorAggressiveVariant, MyapiModelBehaviorOtherVariant),
            "MyapiModelBehavior",
        )

    @model_serializer
    def _serialize(self):
        return _serialize_externally_tagged(
            self.root,
            {
                "Calm": (lambda r: r == "Calm", lambda r: "Calm"),
                "Aggressive": (
                    lambda r: isinstance(r, MyapiModelBehaviorAggressiveVariant),
                    lambda r: {"Aggressive": [r.field_0, r.field_1]},
                ),
                "Other": (
                    lambda r: isinstance(r, MyapiModelBehaviorOtherVariant),
                    lambda r: {"Other": r.model_dump(by_alias=True)},
                ),
            },
            "MyapiModelBehavior",
        )


class MyapiModelKindDog(BaseModel):
    """A dog"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal["dog"] = Field(default="dog", description="Discriminator field")
    breed: str = Field(description="breed of the dog")


class MyapiModelKindCat(BaseModel):
    """A cat"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal["cat"] = Field(default="cat", description="Discriminator field")
    lives: int = Field(description="lives left")


class MyapiModelKindBird(BaseModel):
    """Test for unit variants in internally tagged enums"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal["bird"] = Field(default="bird", description="Discriminator field")


class MyapiModelKind(RootModel):
    root: Annotated[
        Union[MyapiModelKindDog, MyapiModelKindCat, MyapiModelKindBird],
        Field(discriminator="type"),
    ]


class MyapiModelInputPet(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str = Field(description="identity")
    kind: myapi.model.Kind = Field(description="kind of pet")
    age: int | None = Field(default=None, description="age of the pet")
    updated_at: datetime | None = None
    behaviors: list[myapi.model.Behavior] | None = Field(
        default=None, description="behaviors of the pet"
    )


class MyapiModelOutputPet(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str = Field(description="identity")
    kind: myapi.model.Kind = Field(description="kind of pet")
    age: int | None = Field(default=None, description="age of the pet")
    updated_at: datetime
    behaviors: list[myapi.model.Behavior] | None = Field(
        default=None, description="behaviors of the pet"
    )


class MyapiProtoHeaders(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    authorization: str = Field(description="Authorization header")


class MyapiProtoInternalError(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    message: str


class MyapiProtoPaginated(BaseModel, Generic[T]):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    items: list[T] = Field(description="slice of a collection")
    cursor: str | None = Field(default=None, description="cursor for getting next page")


class MyapiProtoPetsListRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    limit: int | None = None
    cursor: str | None = None


class MyapiProtoPetsRemoveRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str = Field(description="identity")


class MyapiProtoPetsUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str = Field(description="identity")
    kind: myapi.model.Kind | None = Field(
        default=None, description="kind of pet, non nullable in the model"
    )
    age: ReflectapiOption[int] = Field(
        default=None, description="age of the pet, nullable in the model"
    )
    behaviors: ReflectapiOption[list[myapi.model.Behavior]] = Field(
        default=None, description="behaviors of the pet, nullable in the model"
    )


class MyapiProtoValidationA(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    message: str


class MyapiProtoPetsCreateErrorInvalidIdentityVariant(BaseModel):
    """InvalidIdentity variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    message: str


# Externally tagged enum using RootModel
MyapiProtoPetsCreateErrorVariants = Union[
    Literal["Conflict"],
    Literal["NotAuthorized"],
    MyapiProtoPetsCreateErrorInvalidIdentityVariant,
]


class MyapiProtoPetsCreateError(RootModel[MyapiProtoPetsCreateErrorVariants]):
    """Externally tagged enum"""

    @model_validator(mode="before")
    @classmethod
    def _validate(cls, data):
        return _parse_externally_tagged(
            data,
            {
                "Conflict": "_unit",
                "NotAuthorized": "_unit",
                "InvalidIdentity": lambda v: (
                    MyapiProtoPetsCreateErrorInvalidIdentityVariant(**v)
                ),
            },
            (MyapiProtoPetsCreateErrorInvalidIdentityVariant,),
            "MyapiProtoPetsCreateError",
        )

    @model_serializer
    def _serialize(self):
        return _serialize_externally_tagged(
            self.root,
            {
                "Conflict": (lambda r: r == "Conflict", lambda r: "Conflict"),
                "NotAuthorized": (
                    lambda r: r == "NotAuthorized",
                    lambda r: "NotAuthorized",
                ),
                "InvalidIdentity": (
                    lambda r: isinstance(
                        r, MyapiProtoPetsCreateErrorInvalidIdentityVariant
                    ),
                    lambda r: {"InvalidIdentity": r.model_dump(by_alias=True)},
                ),
            },
            "MyapiProtoPetsCreateError",
        )


class MyapiProtoPetsListErrorInvalidCursor(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    kind: Literal["InvalidCursor"] = Field(
        default="InvalidCursor", description="Discriminator field"
    )


class MyapiProtoPetsListErrorUnauthorized(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    kind: Literal["Unauthorized"] = Field(
        default="Unauthorized", description="Discriminator field"
    )


class MyapiProtoPetsListErrorInternal(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    kind: Literal["Internal"] = Field(
        default="Internal", description="Discriminator field"
    )
    message: str


class MyapiProtoPetsListError(RootModel):
    root: Annotated[
        Union[
            MyapiProtoPetsListErrorInvalidCursor,
            MyapiProtoPetsListErrorUnauthorized,
            MyapiProtoPetsListErrorInternal,
        ],
        Field(discriminator="kind"),
    ]


class MyapiProtoPetsRemoveError(str, Enum):
    """Generated enum."""

    NOT_FOUND = "NotFound"
    NOT_AUTHORIZED = "NotAuthorized"


class MyapiProtoPetsUpdateErrorValidationVariant(BaseModel):
    """Validation variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    field_0: list[myapi.proto.ValidationError]


# Externally tagged enum using RootModel
MyapiProtoPetsUpdateErrorVariants = Union[
    Literal["NotFound"],
    Literal["NotAuthorized"],
    MyapiProtoPetsUpdateErrorValidationVariant,
]


class MyapiProtoPetsUpdateError(RootModel[MyapiProtoPetsUpdateErrorVariants]):
    """Externally tagged enum"""

    @model_validator(mode="before")
    @classmethod
    def _validate(cls, data):
        return _parse_externally_tagged(
            data,
            {
                "NotFound": "_unit",
                "NotAuthorized": "_unit",
                "Validation": lambda v: MyapiProtoPetsUpdateErrorValidationVariant(
                    field_0=v
                ),
            },
            (MyapiProtoPetsUpdateErrorValidationVariant,),
            "MyapiProtoPetsUpdateError",
        )

    @model_serializer
    def _serialize(self):
        return _serialize_externally_tagged(
            self.root,
            {
                "NotFound": (lambda r: r == "NotFound", lambda r: "NotFound"),
                "NotAuthorized": (
                    lambda r: r == "NotAuthorized",
                    lambda r: "NotAuthorized",
                ),
                "Validation": (
                    lambda r: isinstance(r, MyapiProtoPetsUpdateErrorValidationVariant),
                    lambda r: {"Validation": r.field_0},
                ),
            },
            "MyapiProtoPetsUpdateError",
        )


class MyapiProtoValidationErrorValidationAVariant(BaseModel):
    """ValidationA variant"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    field_0: myapi.proto.ValidationA


# Externally tagged enum using RootModel
MyapiProtoValidationErrorVariants = MyapiProtoValidationErrorValidationAVariant


class MyapiProtoValidationError(RootModel[MyapiProtoValidationErrorVariants]):
    """Externally tagged enum"""

    @model_validator(mode="before")
    @classmethod
    def _validate(cls, data):
        return _parse_externally_tagged(
            data,
            {
                "ValidationA": lambda v: MyapiProtoValidationErrorValidationAVariant(
                    field_0=v
                )
            },
            (MyapiProtoValidationErrorValidationAVariant,),
            "MyapiProtoValidationError",
        )

    @model_serializer
    def _serialize(self):
        return _serialize_externally_tagged(
            self.root,
            {
                "ValidationA": (
                    lambda r: isinstance(
                        r, MyapiProtoValidationErrorValidationAVariant
                    ),
                    lambda r: {"ValidationA": r.field_0},
                )
            },
            "MyapiProtoValidationError",
        )


# Namespace classes for dotted access to types
class myapi:
    """Namespace for myapi types."""

    HealthCheckFail = MyapiHealthCheckFail

    class model:
        """Namespace for model types."""

        BehaviorAggressiveVariant = MyapiModelBehaviorAggressiveVariant
        BehaviorOtherVariant = MyapiModelBehaviorOtherVariant
        Behavior = MyapiModelBehavior
        KindDog = MyapiModelKindDog
        KindCat = MyapiModelKindCat
        KindBird = MyapiModelKindBird
        Kind = MyapiModelKind

        class input:
            """Namespace for input types."""

            Pet = MyapiModelInputPet

        class output:
            """Namespace for output types."""

            Pet = MyapiModelOutputPet

    class proto:
        """Namespace for proto types."""

        Headers = MyapiProtoHeaders
        InternalError = MyapiProtoInternalError
        Paginated = MyapiProtoPaginated
        PetsListRequest = MyapiProtoPetsListRequest
        PetsRemoveRequest = MyapiProtoPetsRemoveRequest
        PetsUpdateRequest = MyapiProtoPetsUpdateRequest
        ValidationA = MyapiProtoValidationA
        PetsCreateErrorInvalidIdentityVariant = (
            MyapiProtoPetsCreateErrorInvalidIdentityVariant
        )
        PetsCreateError = MyapiProtoPetsCreateError
        PetsListErrorInvalidCursor = MyapiProtoPetsListErrorInvalidCursor
        PetsListErrorUnauthorized = MyapiProtoPetsListErrorUnauthorized
        PetsListErrorInternal = MyapiProtoPetsListErrorInternal
        PetsListError = MyapiProtoPetsListError
        PetsRemoveError = MyapiProtoPetsRemoveError
        PetsUpdateErrorValidationVariant = MyapiProtoPetsUpdateErrorValidationVariant
        PetsUpdateError = MyapiProtoPetsUpdateError
        ValidationErrorValidationAVariant = MyapiProtoValidationErrorValidationAVariant
        ValidationError = MyapiProtoValidationError


class AsyncHealthClient:
    """Async client for health operations."""

    def __init__(self, client: AsyncClientBase) -> None:
        self._client = client

    async def check(
        self,
    ) -> ApiResponse[Any, myapi.HealthCheckFail]:
        """Check the health of the service

        Returns:
            ApiResponse[Any, myapi.HealthCheckFail]: Success=Any, Error=myapi.HealthCheckFail
        """
        path = "/health.check"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            response_model=None,
            error_model=myapi.HealthCheckFail,
        )


class AsyncPetsClient:
    """Async client for pets operations."""

    def __init__(self, client: AsyncClientBase) -> None:
        self._client = client

    async def create(
        self,
        data: Optional[myapi.model.input.Pet] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any, myapi.proto.PetsCreateError]:
        """Create a new pet

        Args:
            data: Request data for the create operation.

        Returns:
            ApiResponse[Any, myapi.proto.PetsCreateError]: Success=Any, Error=myapi.proto.PetsCreateError
        """
        path = "/pets.create"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
            error_model=myapi.proto.PetsCreateError,
        )

    async def delete(
        self,
        data: Optional[myapi.proto.PetsRemoveRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any, myapi.proto.PetsRemoveError]:
        """Remove an existing pet

        Args:
            data: Request data for the delete operation.

        Returns:
            ApiResponse[Any, myapi.proto.PetsRemoveError]: Success=Any, Error=myapi.proto.PetsRemoveError

        .. deprecated::
           Use pets.remove instead
        """

        warnings.warn(
            "pets_delete is deprecated: Use pets.remove instead",
            DeprecationWarning,
            stacklevel=2,
        )

        path = "/pets.delete"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
            error_model=myapi.proto.PetsRemoveError,
        )

    async def get_first(
        self,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[myapi.model.output.Pet | None, None]:
        """Fetch first pet, if any exists

        Returns:
            ApiResponse[myapi.model.output.Pet | None, None]: Success=myapi.model.output.Pet | None, Error=None
        """
        path = "/pets.get-first"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            headers_model=headers,
            response_model=myapi.model.output.Pet | None,
            error_model=None,
        )

    async def list(
        self,
        data: Optional[myapi.proto.PetsListRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[
        myapi.proto.Paginated[myapi.model.output.Pet], myapi.proto.PetsListError
    ]:
        """List available pets

        Args:
            data: Request data for the list operation.

        Returns:
            ApiResponse[myapi.proto.Paginated[myapi.model.output.Pet], myapi.proto.PetsListError]: Success=myapi.proto.Paginated[myapi.model.output.Pet], Error=myapi.proto.PetsListError
        """
        path = "/pets.list"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=myapi.proto.Paginated[myapi.model.output.Pet],
            error_model=myapi.proto.PetsListError,
        )

    async def remove(
        self,
        data: Optional[myapi.proto.PetsRemoveRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any, myapi.proto.PetsRemoveError]:
        """Remove an existing pet

        Args:
            data: Request data for the remove operation.

        Returns:
            ApiResponse[Any, myapi.proto.PetsRemoveError]: Success=Any, Error=myapi.proto.PetsRemoveError
        """
        path = "/pets.remove"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
            error_model=myapi.proto.PetsRemoveError,
        )

    async def update(
        self,
        data: Optional[myapi.proto.PetsUpdateRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any, myapi.proto.PetsUpdateError]:
        """Update an existing pet

        Args:
            data: Request data for the update operation.

        Returns:
            ApiResponse[Any, myapi.proto.PetsUpdateError]: Success=Any, Error=myapi.proto.PetsUpdateError
        """
        path = "/pets.update"

        params: dict[str, Any] = {}
        return await self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
            error_model=myapi.proto.PetsUpdateError,
        )


class AsyncClient(AsyncClientBase):
    """Async client for the API."""

    def __init__(
        self,
        base_url: str,
        **kwargs: Any,
    ) -> None:
        super().__init__(base_url, **kwargs)

        self.health = AsyncHealthClient(self)

        self.pets = AsyncPetsClient(self)


class HealthClient:
    """Synchronous client for health operations."""

    def __init__(self, client: ClientBase) -> None:
        self._client = client

    def check(
        self,
    ) -> ApiResponse[Any, myapi.HealthCheckFail]:
        """Check the health of the service

        Returns:
            ApiResponse[Any, myapi.HealthCheckFail]: Success=Any, Error=myapi.HealthCheckFail
        """
        path = "/health.check"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            response_model=None,
            error_model=myapi.HealthCheckFail,
        )


class PetsClient:
    """Synchronous client for pets operations."""

    def __init__(self, client: ClientBase) -> None:
        self._client = client

    def create(
        self,
        data: Optional[myapi.model.input.Pet] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any, myapi.proto.PetsCreateError]:
        """Create a new pet

        Args:
            data: Request data for the create operation.

        Returns:
            ApiResponse[Any, myapi.proto.PetsCreateError]: Success=Any, Error=myapi.proto.PetsCreateError
        """
        path = "/pets.create"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
            error_model=myapi.proto.PetsCreateError,
        )

    def delete(
        self,
        data: Optional[myapi.proto.PetsRemoveRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any, myapi.proto.PetsRemoveError]:
        """Remove an existing pet

        Args:
            data: Request data for the delete operation.

        Returns:
            ApiResponse[Any, myapi.proto.PetsRemoveError]: Success=Any, Error=myapi.proto.PetsRemoveError

        .. deprecated::
           Use pets.remove instead
        """

        warnings.warn(
            "pets_delete is deprecated: Use pets.remove instead",
            DeprecationWarning,
            stacklevel=2,
        )

        path = "/pets.delete"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
            error_model=myapi.proto.PetsRemoveError,
        )

    def get_first(
        self,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[myapi.model.output.Pet | None, None]:
        """Fetch first pet, if any exists

        Returns:
            ApiResponse[myapi.model.output.Pet | None, None]: Success=myapi.model.output.Pet | None, Error=None
        """
        path = "/pets.get-first"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            headers_model=headers,
            response_model=myapi.model.output.Pet | None,
            error_model=None,
        )

    def list(
        self,
        data: Optional[myapi.proto.PetsListRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[
        myapi.proto.Paginated[myapi.model.output.Pet], myapi.proto.PetsListError
    ]:
        """List available pets

        Args:
            data: Request data for the list operation.

        Returns:
            ApiResponse[myapi.proto.Paginated[myapi.model.output.Pet], myapi.proto.PetsListError]: Success=myapi.proto.Paginated[myapi.model.output.Pet], Error=myapi.proto.PetsListError
        """
        path = "/pets.list"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=myapi.proto.Paginated[myapi.model.output.Pet],
            error_model=myapi.proto.PetsListError,
        )

    def remove(
        self,
        data: Optional[myapi.proto.PetsRemoveRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any, myapi.proto.PetsRemoveError]:
        """Remove an existing pet

        Args:
            data: Request data for the remove operation.

        Returns:
            ApiResponse[Any, myapi.proto.PetsRemoveError]: Success=Any, Error=myapi.proto.PetsRemoveError
        """
        path = "/pets.remove"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
            error_model=myapi.proto.PetsRemoveError,
        )

    def update(
        self,
        data: Optional[myapi.proto.PetsUpdateRequest] = None,
        headers: Optional[myapi.proto.Headers] = None,
    ) -> ApiResponse[Any, myapi.proto.PetsUpdateError]:
        """Update an existing pet

        Args:
            data: Request data for the update operation.

        Returns:
            ApiResponse[Any, myapi.proto.PetsUpdateError]: Success=Any, Error=myapi.proto.PetsUpdateError
        """
        path = "/pets.update"

        params: dict[str, Any] = {}
        return self._client._make_request(
            "POST",
            path,
            params=params if params else None,
            json_model=data,
            headers_model=headers,
            response_model=None,
            error_model=myapi.proto.PetsUpdateError,
        )


class Client(ClientBase):
    """Synchronous client for the API."""

    def __init__(
        self,
        base_url: str,
        **kwargs: Any,
    ) -> None:
        super().__init__(base_url, **kwargs)

        self.health = HealthClient(self)

        self.pets = PetsClient(self)


# External type definitions
StdNumNonZeroU32 = Annotated[int, "Rust NonZero u32 type"]
StdNumNonZeroU64 = Annotated[int, "Rust NonZero u64 type"]
StdNumNonZeroI32 = Annotated[int, "Rust NonZero i32 type"]
StdNumNonZeroI64 = Annotated[int, "Rust NonZero i64 type"]

# Rebuild models to resolve forward references
for _model in [
    MyapiHealthCheckFail,
    MyapiModelBehavior,
    MyapiModelKind,
    MyapiModelInputPet,
    MyapiModelOutputPet,
    MyapiProtoHeaders,
    MyapiProtoInternalError,
    MyapiProtoPaginated,
    MyapiProtoPetsCreateError,
    MyapiProtoPetsListError,
    MyapiProtoPetsListRequest,
    MyapiProtoPetsRemoveError,
    MyapiProtoPetsRemoveRequest,
    MyapiProtoPetsUpdateError,
    MyapiProtoPetsUpdateRequest,
    MyapiProtoValidationA,
    MyapiProtoValidationError,
]:
    try:
        _model.model_rebuild()
    except Exception:
        pass
