// DO NOT MODIFY THIS FILE MANUALLY
// This file was generated by reflect-cli
//
// Schema name: Demo application
// This is a demo application




export namespace myapi {

export type ExampleError =
    | "Error1"
    ;


export interface ExampleRequestHeaders {
    name: string;
    }


export interface ExampleResponse {
    /// some doc
    message: string;
    }


export namespace input {

/// Some example doc
/// test
export interface ExampleRequest {
    inputData: string;
    input_optional: string | null;
    }

}

export namespace output {

/// Some example doc
/// test
export interface ExampleRequest {
    inputData: string;
    }

}
}

export namespace reflect {

/// Struct object with no fields
export interface Empty {
    }


/// Error object which is expected to be never returned
export interface Infallible {
    }

}



