[package]
name = "reflectapi-demo-client-generated"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflectapi = { workspace = true }

bytes = "1.5.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.116"

http = "1.1.0"

reqwest = { version = "0.12.2", optional = true }

[features]
reqwest = ["dep:reqwest"]
