[package]
name = "reflectapi-demo-client-generated"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflectapi = { workspace = true, features = ["rt", "reqwest"] }
serde = { version = "1.0.197", features = ["derive"] }

