[package]
name = "reflectapi-demo-client-generated"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
reflectapi = { workspace = true, features = ["rt", "reqwest"] }
tracing = "0.1"
serde = { version = "1.0.197", features = ["derive"] }

