[package]
name = "reflectapi-demo-client-generated"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
reflectapi = { workspace = true, features = ["rt", "reqwest", "chrono"] }
chrono = { version = "0.4.37", features = ["serde"] }
tracing = "0.1"
serde = { version = "1.0.218", features = ["derive"] }

