[package]
name = "reflectapi-demo-client"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
reflectapi-demo-client-generated = { path = "generated" }

tokio = { version = "1.38.0", features = ["full"] }
reqwest = { version = "0.12.2" }

reflectapi.workspace = true
