"""
DO NOT MODIFY THIS FILE MANUALLY
This file was generated by reflectapi-cli

Schema name: Demo application
This is a demo application
"""

from __future__ import annotations


# Standard library imports
import warnings
from collections.abc import AsyncIterator, Iterator
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Generic, Literal, Optional, TypeVar, Union

# Third-party imports
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    model_serializer,
    model_validator,
)

# Runtime imports
from reflectapi_runtime import AsyncClientBase, ClientBase, ApiResponse
from reflectapi_runtime import ReflectapiDuration
from reflectapi_runtime import ReflectapiEmpty
from reflectapi_runtime import ReflectapiInfallible
from reflectapi_runtime import ReflectapiPartialModel
from reflectapi_runtime import (
    parse_externally_tagged as _parse_externally_tagged,
    serialize_externally_tagged as _serialize_externally_tagged,
)


# Type variables for generic types


C = TypeVar("C")

T = TypeVar("T")


# External type definitions
StdNumNonZeroU32 = Annotated[int, "Rust NonZero u32 type"]
StdNumNonZeroU64 = Annotated[int, "Rust NonZero u64 type"]
StdNumNonZeroI32 = Annotated[int, "Rust NonZero i32 type"]
StdNumNonZeroI64 = Annotated[int, "Rust NonZero i64 type"]


class MyapiAdversarialRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    keywords: myapi.adversarial.PyKeywordFields
    reserved: myapi.adversarial.PydanticReservedFields
    tree: myapi.adversarial.TreeNode
    mutual: myapi.adversarial.MutualA
    generic_tree: myapi.adversarial.GenericTree[int]
    keyword_variants: myapi.adversarial.KeywordVariants
    int_keyed: myapi.adversarial.IntKeyedMap
    user_id: int
    deep_option: myapi.adversarial.DeepOption
    shadowing: myapi.adversarial.ShadowingFields
    empty: myapi.adversarial.EmptyStruct
    weird_doc: myapi.adversarial.WeirdDocstring
    shadow_base_model: myapi.adversarial.BaseModel
    wrapper_int: myapi.adversarial.Wrapper[int]
    wrapper_str: myapi.adversarial.Wrapper[str]
    defaulted: myapi.adversarial.DefaultedField


class MyapiAdversarialResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    ok: bool


class MyapiAdversarialBaseModel(BaseModel):
    """The generated module imports `BaseModel`, `Field`, `Annotated`,
    `Generic`, `TypeVar` from `pydantic`/`typing`. A user struct
    with one of those names must not break the module."""

    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    label: str


class MyapiAdversarialDeepOption(ReflectapiPartialModel):
    model_config = ConfigDict(
        extra="ignore",
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    maybe_maybe: str | None | None = None


class MyapiAdversarialDefaultedField(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    count: int | None = None


class MyapiAdversarialEmptyStruct(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )


class MyapiAdversarialGenericTree(BaseModel, Generic[T]):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    value: T
    children: list[myapi.adversarial.GenericTree[T]]


class MyapiAdversarialIntKeyedMap(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    by_id: dict[int, str]
    uuid_keyed: dict[str, str]


class MyapiAdversarialMutualA(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    name: str
    b: myapi.adversarial.MutualB | None = None


class MyapiAdversarialMutualB(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    name: str
    a: myapi.adversarial.MutualA | None = None


class MyapiAdversarialPyKeywordFields(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    class_: str = Field(serialization_alias="class", validation_alias="class")
    from_: int = Field(serialization_alias="from", validation_alias="from")
    import_: bool = Field(serialization_alias="import", validation_alias="import")
    lambda_: int = Field(serialization_alias="lambda", validation_alias="lambda")
    return_: list[int] = Field(serialization_alias="return", validation_alias="return")
    yield_: str | None = Field(
        default=None, serialization_alias="yield", validation_alias="yield"
    )
    none: int | None = Field(
        default=None, serialization_alias="None", validation_alias="None"
    )
    true: bool = Field(serialization_alias="True", validation_alias="True")
    type_: str = Field(serialization_alias="type", validation_alias="type")
    match: str


class MyapiAdversarialPydanticReservedFields(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    model_config_: str = Field(
        serialization_alias="model_config", validation_alias="model_config"
    )
    model_fields_set_: str = Field(
        serialization_alias="model_fields_set", validation_alias="model_fields_set"
    )
    model_dump_json_: str = Field(
        serialization_alias="model_dump_json", validation_alias="model_dump_json"
    )


class MyapiAdversarialShadowingFields(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    field: str
    annotated: str
    generic: str
    base_model: str


class MyapiAdversarialTreeNode(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    value: str
    children: list[myapi.adversarial.TreeNode]
    parent: myapi.adversarial.TreeNode | None = None


class MyapiAdversarialWeirdDocstring(BaseModel):
    """A docstring with \\"quotes\\" and \\'apostrophes\\' and a backslash: \\\\\\\\
And a \\"\\"\\"triple quote\\"\\"\\" inside."""

    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    value: str


class MyapiAdversarialWrapper(BaseModel, Generic[T]):
    """Each monomorphisation must produce a distinct Python class.
    Shared-name collapse would mean the second usage\\'s fields would
    silently shadow the first."""

    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    inner: T


class MyapiAdversarialKeywordVariantsClass(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    kind: Literal["class"] = Field(default="class", description="Discriminator field")


class MyapiAdversarialKeywordVariantsLambda(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    kind: Literal["lambda"] = Field(default="lambda", description="Discriminator field")
    name: str


class MyapiAdversarialKeywordVariantsReturn(BaseModel):
    model_config = ConfigDict(
        extra="ignore", populate_by_name=True, protected_namespaces=()
    )

    kind: Literal["return"] = Field(default="return", description="Discriminator field")
    value: int


class MyapiAdversarialKeywordVariants(RootModel):
    root: Annotated[
        Union[
            MyapiAdversarialKeywordVariantsClass,
            MyapiAdversarialKeywordVariantsLambda,
            MyapiAdversarialKeywordVariantsReturn,
        ],
        Field(discriminator="kind"),
    ]


# Public aliases for this module
AdversarialRequest = MyapiAdversarialRequest
AdversarialResponse = MyapiAdversarialResponse
BaseModel = MyapiAdversarialBaseModel
DeepOption = MyapiAdversarialDeepOption
DefaultedField = MyapiAdversarialDefaultedField
EmptyStruct = MyapiAdversarialEmptyStruct
GenericTree = MyapiAdversarialGenericTree
IntKeyedMap = MyapiAdversarialIntKeyedMap
KeywordVariants = MyapiAdversarialKeywordVariants
KeywordVariantsClass = MyapiAdversarialKeywordVariantsClass
KeywordVariantsLambda = MyapiAdversarialKeywordVariantsLambda
KeywordVariantsReturn = MyapiAdversarialKeywordVariantsReturn
MutualA = MyapiAdversarialMutualA
MutualB = MyapiAdversarialMutualB
PyKeywordFields = MyapiAdversarialPyKeywordFields
PydanticReservedFields = MyapiAdversarialPydanticReservedFields
Request = MyapiAdversarialRequest
Response = MyapiAdversarialResponse
ShadowingFields = MyapiAdversarialShadowingFields
TreeNode = MyapiAdversarialTreeNode
WeirdDocstring = MyapiAdversarialWeirdDocstring
Wrapper = MyapiAdversarialWrapper

__all__ = [
    "AdversarialRequest",
    "AdversarialResponse",
    "BaseModel",
    "DeepOption",
    "DefaultedField",
    "EmptyStruct",
    "GenericTree",
    "IntKeyedMap",
    "KeywordVariants",
    "KeywordVariantsClass",
    "KeywordVariantsLambda",
    "KeywordVariantsReturn",
    "MutualA",
    "MutualB",
    "MyapiAdversarialBaseModel",
    "MyapiAdversarialDeepOption",
    "MyapiAdversarialDefaultedField",
    "MyapiAdversarialEmptyStruct",
    "MyapiAdversarialGenericTree",
    "MyapiAdversarialIntKeyedMap",
    "MyapiAdversarialKeywordVariants",
    "MyapiAdversarialKeywordVariantsClass",
    "MyapiAdversarialKeywordVariantsLambda",
    "MyapiAdversarialKeywordVariantsReturn",
    "MyapiAdversarialMutualA",
    "MyapiAdversarialMutualB",
    "MyapiAdversarialPyKeywordFields",
    "MyapiAdversarialPydanticReservedFields",
    "MyapiAdversarialRequest",
    "MyapiAdversarialResponse",
    "MyapiAdversarialShadowingFields",
    "MyapiAdversarialTreeNode",
    "MyapiAdversarialWeirdDocstring",
    "MyapiAdversarialWrapper",
    "PyKeywordFields",
    "PydanticReservedFields",
    "Request",
    "Response",
    "ShadowingFields",
    "TreeNode",
    "WeirdDocstring",
    "Wrapper",
]
