[package]
name = "reflect-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflect-derive.workspace = true

serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
trybuild = "1.0.0"
insta = "1.36.1"
