"""
DO NOT MODIFY THIS FILE MANUALLY
This file was generated by reflectapi-cli

Schema name: Demo application
This is a demo application
"""

from __future__ import annotations


# Standard library imports
import warnings
from collections.abc import AsyncIterator, Iterator
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Generic, Literal, Optional, TypeVar, Union

# Third-party imports
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    model_serializer,
    model_validator,
)

# Runtime imports
from reflectapi_runtime import AsyncClientBase, ClientBase, ApiResponse
from reflectapi_runtime import ReflectapiDuration
from reflectapi_runtime import ReflectapiEmpty
from reflectapi_runtime import ReflectapiInfallible
from reflectapi_runtime import ReflectapiPartialModel
from reflectapi_runtime import (
    parse_externally_tagged as _parse_externally_tagged,
    serialize_externally_tagged as _serialize_externally_tagged,
)


# Type variables for generic types


C = TypeVar("C")

T = TypeVar("T")


# External type definitions
StdNumNonZeroU32 = Annotated[int, "Rust NonZero u32 type"]
StdNumNonZeroU64 = Annotated[int, "Rust NonZero u64 type"]
StdNumNonZeroI32 = Annotated[int, "Rust NonZero i32 type"]
StdNumNonZeroI64 = Annotated[int, "Rust NonZero i64 type"]


class ReflectapiOptionUndefined(BaseModel):
    """The value is missing, i.e. undefined in JavaScript"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)


class ReflectapiOptionNone(BaseModel):
    """The value is provided but set to none, i.e. null in JavaScript"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)


class ReflectapiOptionSome(BaseModel):
    """The value is provided and set to some value"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    value: T | None = None


ReflectapiOption = Union[
    ReflectapiOptionUndefined, ReflectapiOptionNone, ReflectapiOptionSome
]
"""Undefinable Option type"""


# Public aliases for this module
Option = ReflectapiOption
OptionNone = ReflectapiOptionNone
OptionSome = ReflectapiOptionSome
OptionUndefined = ReflectapiOptionUndefined

try:
    from .._rebuild import rebuild_models as _rebuild_models

    _rebuild_models()
except ImportError:
    pass

__all__ = [
    "Option",
    "OptionNone",
    "OptionSome",
    "OptionUndefined",
    "ReflectapiOption",
    "ReflectapiOptionNone",
    "ReflectapiOptionSome",
    "ReflectapiOptionUndefined",
]
