name = "reflectapi-docs"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# Static Assets configuration for mdBook output
[assets]
directory = "./book"
binding = "ASSETS"

# If/when we want to host at a custom domain, uncomment and fill in routes
# routes = [
#   { pattern = "docs.reflectapi.dev/*", zone_name = "reflectapi.dev" }
# ]