[package]
name = "reflect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflect-derive.workspace = true
reflect-schema.workspace = true

uuid = { version = "1.7.0", optional = true }

[features]
uuid = ["dep:uuid"]
