POST http://localhost:3000/pets.create
Content-Type:  application/json; charset=utf-8
Authorization: password
traceparent:   blah
name: 1

{"name":"Bobby","kind":{"type":"dog", "breed":"labrador"},"age":1,"behaviors":[]}

###

GET http://localhost:3000/pets.list
Content-Type: application/json
Authorization: password
traceparent: blah

{}
