name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust:
    name: Rust format, lint, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # NOTE: When updating the biome version, also update reflectapi/src/codegen/typescript.rs
      - uses: biomejs/setup-biome@v2
        with:
          version: "1.8.3"
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --workspace

  python-runtime:
    name: Python runtime tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Run tests
        working-directory: reflectapi-python-runtime
        run: uv run --extra dev pytest -q --no-cov
